//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 12:32:33 PM CDT 
//


package com.oadr2.b;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eiEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eiEventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}eventDescriptor"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}eiActivePeriod"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}eiEventSignals"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}eiTarget"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eiEventType", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110", propOrder = {
    "eventDescriptor",
    "eiActivePeriod",
    "eiEventSignals",
    "eiTarget"
})
@XmlRootElement(name = "eiEvent", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110")
public class EiEvent {

    @XmlElement(required = true)
    protected EventDescriptor eventDescriptor;
    @XmlElement(required = true)
    protected EiActivePeriod eiActivePeriod;
    @XmlElement(required = true)
    protected EiEventSignals eiEventSignals;
    @XmlElement(required = true)
    protected EiTargetType eiTarget;

    /**
     * Gets the value of the eventDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link EventDescriptor }
     *     
     */
    public EventDescriptor getEventDescriptor() {
        return eventDescriptor;
    }

    /**
     * Sets the value of the eventDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDescriptor }
     *     
     */
    public void setEventDescriptor(EventDescriptor value) {
        this.eventDescriptor = value;
    }

    /**
     * Gets the value of the eiActivePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link EiActivePeriod }
     *     
     */
    public EiActivePeriod getEiActivePeriod() {
        return eiActivePeriod;
    }

    /**
     * Sets the value of the eiActivePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link EiActivePeriod }
     *     
     */
    public void setEiActivePeriod(EiActivePeriod value) {
        this.eiActivePeriod = value;
    }

    /**
     * Gets the value of the eiEventSignals property.
     * 
     * @return
     *     possible object is
     *     {@link EiEventSignals }
     *     
     */
    public EiEventSignals getEiEventSignals() {
        return eiEventSignals;
    }

    /**
     * Sets the value of the eiEventSignals property.
     * 
     * @param value
     *     allowed object is
     *     {@link EiEventSignals }
     *     
     */
    public void setEiEventSignals(EiEventSignals value) {
        this.eiEventSignals = value;
    }

    /**
     * Gets the value of the eiTarget property.
     * 
     * @return
     *     possible object is
     *     {@link EiTargetType }
     *     
     */
    public EiTargetType getEiTarget() {
        return eiTarget;
    }

    /**
     * Sets the value of the eiTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link EiTargetType }
     *     
     */
    public void setEiTarget(EiTargetType value) {
        this.eiTarget = value;
    }

}
