//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 12:32:33 PM CDT 
//


package com.oadr2.b;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eiEventSignalsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eiEventSignalsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}eiEventSignal" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}eiEventBaseline" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eiEventSignalsType", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110", propOrder = {
    "eiEventSignals",
    "eiEventBaseline"
})
@XmlRootElement(name = "eiEventSignals", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110")
public class EiEventSignals {

    @XmlElement(name = "eiEventSignal", required = true)
    protected List<EiEventSignal> eiEventSignals;
    protected EiEventBaseline eiEventBaseline;

    /**
     * Interval data for an event Gets the value of the eiEventSignals property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eiEventSignals property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEiEventSignals().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EiEventSignal }
     * 
     * 
     */
    public List<EiEventSignal> getEiEventSignals() {
        if (eiEventSignals == null) {
            eiEventSignals = new ArrayList<EiEventSignal>();
        }
        return this.eiEventSignals;
    }

    /**
     * Interval data for a baseline
     * 
     * @return
     *     possible object is
     *     {@link EiEventBaseline }
     *     
     */
    public EiEventBaseline getEiEventBaseline() {
        return eiEventBaseline;
    }

    /**
     * Sets the value of the eiEventBaseline property.
     * 
     * @param value
     *     allowed object is
     *     {@link EiEventBaseline }
     *     
     */
    public void setEiEventBaseline(EiEventBaseline value) {
        this.eiEventBaseline = value;
    }

}
