//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 12:32:33 PM CDT 
//


package com.oadr2.b;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.oadr2.b.xcal.Dtstart;
import com.oadr2.b.xcal.DurationPropType;
import com.oadr2.b.xcal.Uid;


/**
 * <p>Java class for IntervalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IntervalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:ietf:params:xml:ns:icalendar-2.0}dtstart" minOccurs="0"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:icalendar-2.0}duration" minOccurs="0"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:icalendar-2.0}uid" minOccurs="0"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:icalendar-2.0:stream}streamPayloadBase" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntervalType", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110", propOrder = {
    "dtstart",
    "duration",
    "uid",
    "streamPayloadBases"
})
@XmlRootElement(name = "interval", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110")
public class Interval {

    @XmlElement(namespace = "urn:ietf:params:xml:ns:icalendar-2.0")
    protected Dtstart dtstart;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:icalendar-2.0")
    protected DurationPropType duration;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:icalendar-2.0")
    protected Uid uid;
    @XmlElementRef(name = "streamPayloadBase", namespace = "urn:ietf:params:xml:ns:icalendar-2.0:stream", type = JAXBElement.class)
    protected List<JAXBElement<? extends StreamPayloadBaseType>> streamPayloadBases;

    /**
     * Gets the value of the dtstart property.
     * 
     * @return
     *     possible object is
     *     {@link Dtstart }
     *     
     */
    public Dtstart getDtstart() {
        return dtstart;
    }

    /**
     * Sets the value of the dtstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dtstart }
     *     
     */
    public void setDtstart(Dtstart value) {
        this.dtstart = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link DurationPropType }
     *     
     */
    public DurationPropType getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationPropType }
     *     
     */
    public void setDuration(DurationPropType value) {
        this.duration = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link Uid }
     *     
     */
    public Uid getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uid }
     *     
     */
    public void setUid(Uid value) {
        this.uid = value;
    }

    /**
     * Gets the value of the streamPayloadBases property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the streamPayloadBases property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStreamPayloadBases().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link StreamPayloadBaseType }{@code >}
     * {@link JAXBElement }{@code <}{@link SignalPayloadType }{@code >}
     * {@link JAXBElement }{@code <}{@link OadrReportPayloadType }{@code >}
     * {@link JAXBElement }{@code <}{@link OadrGBStreamPayloadBase }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends StreamPayloadBaseType>> getStreamPayloadBases() {
        if (streamPayloadBases == null) {
            streamPayloadBases = new ArrayList<JAXBElement<? extends StreamPayloadBaseType>>();
        }
        return this.streamPayloadBases;
    }

    public void setStreamPayloadBases(JAXBElement<? extends StreamPayloadBaseType> ...elements){
    	 if (streamPayloadBases == null) {
             streamPayloadBases = new ArrayList<JAXBElement<? extends StreamPayloadBaseType>>();
         }
    	 for(int i=0; i< elements.length; i++){
    		 streamPayloadBases.add(elements[i]);
    	 }
    }
}
