//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 12:32:33 PM CDT 
//


package com.oadr2.b;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrDistributeEvent"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrCreatedEvent"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrRequestEvent"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrResponse"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrCancelOpt"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrCanceledOpt"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrCreateOpt"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrCreatedOpt"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrCancelReport"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrCanceledReport"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrCreateReport"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrCreatedReport"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrRegisterReport"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrRegisteredReport"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrUpdateReport"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrUpdatedReport"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrCancelPartyRegistration"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrCanceledPartyRegistration"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrCreatePartyRegistration"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrCreatedPartyRegistration"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrRequestReregistration"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrQueryRegistration"/>
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrPoll"/>
 *       &lt;/choice>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oadrPoll",
    "oadrQueryRegistration",
    "oadrRequestReregistration",
    "oadrCreatedPartyRegistration",
    "oadrCreatePartyRegistration",
    "oadrCanceledPartyRegistration",
    "oadrCancelPartyRegistration",
    "oadrUpdatedReport",
    "oadrUpdateReport",
    "oadrRegisteredReport",
    "oadrRegisterReport",
    "oadrCreatedReport",
    "oadrCreateReport",
    "oadrCanceledReport",
    "oadrCancelReport",
    "oadrCreatedOpt",
    "oadrCreateOpt",
    "oadrCanceledOpt",
    "oadrCancelOpt",
    "oadrResponse",
    "oadrRequestEvent",
    "oadrCreatedEvent",
    "oadrDistributeEvent"
})
@XmlRootElement(name = "oadrSignedObject")
public class OadrSignedObject {

    protected OadrPoll oadrPoll;
    protected OadrQueryRegistration oadrQueryRegistration;
    protected OadrRequestReregistration oadrRequestReregistration;
    protected OadrCreatedPartyRegistration oadrCreatedPartyRegistration;
    protected OadrCreatePartyRegistration oadrCreatePartyRegistration;
    protected OadrCanceledPartyRegistration oadrCanceledPartyRegistration;
    protected OadrCancelPartyRegistration oadrCancelPartyRegistration;
    protected OadrUpdatedReport oadrUpdatedReport;
    protected OadrUpdateReport oadrUpdateReport;
    protected OadrRegisteredReport oadrRegisteredReport;
    protected OadrRegisterReport oadrRegisterReport;
    protected OadrCreatedReport oadrCreatedReport;
    protected OadrCreateReport oadrCreateReport;
    protected OadrCanceledReport oadrCanceledReport;
    protected OadrCancelReport oadrCancelReport;
    protected OadrCreatedOpt oadrCreatedOpt;
    protected OadrCreateOpt oadrCreateOpt;
    protected OadrCanceledOpt oadrCanceledOpt;
    protected OadrCancelOpt oadrCancelOpt;
    protected OadrResponse oadrResponse;
    protected OadrRequestEvent oadrRequestEvent;
    protected OadrCreatedEvent oadrCreatedEvent;
    protected OadrDistributeEvent oadrDistributeEvent;
    @XmlAttribute(name = "Id", namespace = "http://openadr.org/oadr-2.0b/2012/07")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the oadrPoll property.
     * 
     * @return
     *     possible object is
     *     {@link OadrPoll }
     *     
     */
    public OadrPoll getOadrPoll() {
        return oadrPoll;
    }

    /**
     * Sets the value of the oadrPoll property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrPoll }
     *     
     */
    public void setOadrPoll(OadrPoll value) {
        this.oadrPoll = value;
    }

    /**
     * Gets the value of the oadrQueryRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link OadrQueryRegistration }
     *     
     */
    public OadrQueryRegistration getOadrQueryRegistration() {
        return oadrQueryRegistration;
    }

    /**
     * Sets the value of the oadrQueryRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrQueryRegistration }
     *     
     */
    public void setOadrQueryRegistration(OadrQueryRegistration value) {
        this.oadrQueryRegistration = value;
    }

    /**
     * Gets the value of the oadrRequestReregistration property.
     * 
     * @return
     *     possible object is
     *     {@link OadrRequestReregistration }
     *     
     */
    public OadrRequestReregistration getOadrRequestReregistration() {
        return oadrRequestReregistration;
    }

    /**
     * Sets the value of the oadrRequestReregistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrRequestReregistration }
     *     
     */
    public void setOadrRequestReregistration(OadrRequestReregistration value) {
        this.oadrRequestReregistration = value;
    }

    /**
     * Gets the value of the oadrCreatedPartyRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link OadrCreatedPartyRegistration }
     *     
     */
    public OadrCreatedPartyRegistration getOadrCreatedPartyRegistration() {
        return oadrCreatedPartyRegistration;
    }

    /**
     * Sets the value of the oadrCreatedPartyRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrCreatedPartyRegistration }
     *     
     */
    public void setOadrCreatedPartyRegistration(OadrCreatedPartyRegistration value) {
        this.oadrCreatedPartyRegistration = value;
    }

    /**
     * Gets the value of the oadrCreatePartyRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link OadrCreatePartyRegistration }
     *     
     */
    public OadrCreatePartyRegistration getOadrCreatePartyRegistration() {
        return oadrCreatePartyRegistration;
    }

    /**
     * Sets the value of the oadrCreatePartyRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrCreatePartyRegistration }
     *     
     */
    public void setOadrCreatePartyRegistration(OadrCreatePartyRegistration value) {
        this.oadrCreatePartyRegistration = value;
    }

    /**
     * Gets the value of the oadrCanceledPartyRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link OadrCanceledPartyRegistration }
     *     
     */
    public OadrCanceledPartyRegistration getOadrCanceledPartyRegistration() {
        return oadrCanceledPartyRegistration;
    }

    /**
     * Sets the value of the oadrCanceledPartyRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrCanceledPartyRegistration }
     *     
     */
    public void setOadrCanceledPartyRegistration(OadrCanceledPartyRegistration value) {
        this.oadrCanceledPartyRegistration = value;
    }

    /**
     * Gets the value of the oadrCancelPartyRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link OadrCancelPartyRegistration }
     *     
     */
    public OadrCancelPartyRegistration getOadrCancelPartyRegistration() {
        return oadrCancelPartyRegistration;
    }

    /**
     * Sets the value of the oadrCancelPartyRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrCancelPartyRegistration }
     *     
     */
    public void setOadrCancelPartyRegistration(OadrCancelPartyRegistration value) {
        this.oadrCancelPartyRegistration = value;
    }

    /**
     * Gets the value of the oadrUpdatedReport property.
     * 
     * @return
     *     possible object is
     *     {@link OadrUpdatedReport }
     *     
     */
    public OadrUpdatedReport getOadrUpdatedReport() {
        return oadrUpdatedReport;
    }

    /**
     * Sets the value of the oadrUpdatedReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrUpdatedReport }
     *     
     */
    public void setOadrUpdatedReport(OadrUpdatedReport value) {
        this.oadrUpdatedReport = value;
    }

    /**
     * Gets the value of the oadrUpdateReport property.
     * 
     * @return
     *     possible object is
     *     {@link OadrUpdateReport }
     *     
     */
    public OadrUpdateReport getOadrUpdateReport() {
        return oadrUpdateReport;
    }

    /**
     * Sets the value of the oadrUpdateReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrUpdateReport }
     *     
     */
    public void setOadrUpdateReport(OadrUpdateReport value) {
        this.oadrUpdateReport = value;
    }

    /**
     * Gets the value of the oadrRegisteredReport property.
     * 
     * @return
     *     possible object is
     *     {@link OadrRegisteredReport }
     *     
     */
    public OadrRegisteredReport getOadrRegisteredReport() {
        return oadrRegisteredReport;
    }

    /**
     * Sets the value of the oadrRegisteredReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrRegisteredReport }
     *     
     */
    public void setOadrRegisteredReport(OadrRegisteredReport value) {
        this.oadrRegisteredReport = value;
    }

    /**
     * Gets the value of the oadrRegisterReport property.
     * 
     * @return
     *     possible object is
     *     {@link OadrRegisterReport }
     *     
     */
    public OadrRegisterReport getOadrRegisterReport() {
        return oadrRegisterReport;
    }

    /**
     * Sets the value of the oadrRegisterReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrRegisterReport }
     *     
     */
    public void setOadrRegisterReport(OadrRegisterReport value) {
        this.oadrRegisterReport = value;
    }

    /**
     * Gets the value of the oadrCreatedReport property.
     * 
     * @return
     *     possible object is
     *     {@link OadrCreatedReport }
     *     
     */
    public OadrCreatedReport getOadrCreatedReport() {
        return oadrCreatedReport;
    }

    /**
     * Sets the value of the oadrCreatedReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrCreatedReport }
     *     
     */
    public void setOadrCreatedReport(OadrCreatedReport value) {
        this.oadrCreatedReport = value;
    }

    /**
     * Gets the value of the oadrCreateReport property.
     * 
     * @return
     *     possible object is
     *     {@link OadrCreateReport }
     *     
     */
    public OadrCreateReport getOadrCreateReport() {
        return oadrCreateReport;
    }

    /**
     * Sets the value of the oadrCreateReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrCreateReport }
     *     
     */
    public void setOadrCreateReport(OadrCreateReport value) {
        this.oadrCreateReport = value;
    }

    /**
     * Gets the value of the oadrCanceledReport property.
     * 
     * @return
     *     possible object is
     *     {@link OadrCanceledReport }
     *     
     */
    public OadrCanceledReport getOadrCanceledReport() {
        return oadrCanceledReport;
    }

    /**
     * Sets the value of the oadrCanceledReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrCanceledReport }
     *     
     */
    public void setOadrCanceledReport(OadrCanceledReport value) {
        this.oadrCanceledReport = value;
    }

    /**
     * Gets the value of the oadrCancelReport property.
     * 
     * @return
     *     possible object is
     *     {@link OadrCancelReport }
     *     
     */
    public OadrCancelReport getOadrCancelReport() {
        return oadrCancelReport;
    }

    /**
     * Sets the value of the oadrCancelReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrCancelReport }
     *     
     */
    public void setOadrCancelReport(OadrCancelReport value) {
        this.oadrCancelReport = value;
    }

    /**
     * Gets the value of the oadrCreatedOpt property.
     * 
     * @return
     *     possible object is
     *     {@link OadrCreatedOpt }
     *     
     */
    public OadrCreatedOpt getOadrCreatedOpt() {
        return oadrCreatedOpt;
    }

    /**
     * Sets the value of the oadrCreatedOpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrCreatedOpt }
     *     
     */
    public void setOadrCreatedOpt(OadrCreatedOpt value) {
        this.oadrCreatedOpt = value;
    }

    /**
     * Gets the value of the oadrCreateOpt property.
     * 
     * @return
     *     possible object is
     *     {@link OadrCreateOpt }
     *     
     */
    public OadrCreateOpt getOadrCreateOpt() {
        return oadrCreateOpt;
    }

    /**
     * Sets the value of the oadrCreateOpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrCreateOpt }
     *     
     */
    public void setOadrCreateOpt(OadrCreateOpt value) {
        this.oadrCreateOpt = value;
    }

    /**
     * Gets the value of the oadrCanceledOpt property.
     * 
     * @return
     *     possible object is
     *     {@link OadrCanceledOpt }
     *     
     */
    public OadrCanceledOpt getOadrCanceledOpt() {
        return oadrCanceledOpt;
    }

    /**
     * Sets the value of the oadrCanceledOpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrCanceledOpt }
     *     
     */
    public void setOadrCanceledOpt(OadrCanceledOpt value) {
        this.oadrCanceledOpt = value;
    }

    /**
     * Gets the value of the oadrCancelOpt property.
     * 
     * @return
     *     possible object is
     *     {@link OadrCancelOpt }
     *     
     */
    public OadrCancelOpt getOadrCancelOpt() {
        return oadrCancelOpt;
    }

    /**
     * Sets the value of the oadrCancelOpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrCancelOpt }
     *     
     */
    public void setOadrCancelOpt(OadrCancelOpt value) {
        this.oadrCancelOpt = value;
    }

    /**
     * Gets the value of the oadrResponse property.
     * 
     * @return
     *     possible object is
     *     {@link OadrResponse }
     *     
     */
    public OadrResponse getOadrResponse() {
        return oadrResponse;
    }

    /**
     * Sets the value of the oadrResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrResponse }
     *     
     */
    public void setOadrResponse(OadrResponse value) {
        this.oadrResponse = value;
    }

    /**
     * Gets the value of the oadrRequestEvent property.
     * 
     * @return
     *     possible object is
     *     {@link OadrRequestEvent }
     *     
     */
    public OadrRequestEvent getOadrRequestEvent() {
        return oadrRequestEvent;
    }

    /**
     * Sets the value of the oadrRequestEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrRequestEvent }
     *     
     */
    public void setOadrRequestEvent(OadrRequestEvent value) {
        this.oadrRequestEvent = value;
    }

    /**
     * Gets the value of the oadrCreatedEvent property.
     * 
     * @return
     *     possible object is
     *     {@link OadrCreatedEvent }
     *     
     */
    public OadrCreatedEvent getOadrCreatedEvent() {
        return oadrCreatedEvent;
    }

    /**
     * Sets the value of the oadrCreatedEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrCreatedEvent }
     *     
     */
    public void setOadrCreatedEvent(OadrCreatedEvent value) {
        this.oadrCreatedEvent = value;
    }

    /**
     * Gets the value of the oadrDistributeEvent property.
     * 
     * @return
     *     possible object is
     *     {@link OadrDistributeEvent }
     *     
     */
    public OadrDistributeEvent getOadrDistributeEvent() {
        return oadrDistributeEvent;
    }

    /**
     * Sets the value of the oadrDistributeEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link OadrDistributeEvent }
     *     
     */
    public void setOadrDistributeEvent(OadrDistributeEvent value) {
        this.oadrDistributeEvent = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
