//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 12:32:33 PM CDT 
//


package com.oadr2.b;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="oadrProfile" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrProfileName"/>
 *                   &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrTransports"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oadrProfiles"
})
@XmlRootElement(name = "oadrProfiles")
public class OadrProfiles {

    @XmlElement(name = "oadrProfile", required = true)
    protected List<OadrProfiles.OadrProfile> oadrProfiles;

    /**
     * Gets the value of the oadrProfiles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oadrProfiles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOadrProfiles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OadrProfiles.OadrProfile }
     * 
     * 
     */
    public List<OadrProfiles.OadrProfile> getOadrProfiles() {
        if (oadrProfiles == null) {
            oadrProfiles = new ArrayList<OadrProfiles.OadrProfile>();
        }
        return this.oadrProfiles;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrProfileName"/>
     *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrTransports"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "oadrProfileName",
        "oadrTransports"
    })
    public static class OadrProfile {

        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String oadrProfileName;
        @XmlElement(required = true)
        protected OadrTransports oadrTransports;

        /**
         * Gets the value of the oadrProfileName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOadrProfileName() {
            return oadrProfileName;
        }

        /**
         * Sets the value of the oadrProfileName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOadrProfileName(String value) {
            this.oadrProfileName = value;
        }

        /**
         * Gets the value of the oadrTransports property.
         * 
         * @return
         *     possible object is
         *     {@link OadrTransports }
         *     
         */
        public OadrTransports getOadrTransports() {
            return oadrTransports;
        }

        /**
         * Sets the value of the oadrTransports property.
         * 
         * @param value
         *     allowed object is
         *     {@link OadrTransports }
         *     
         */
        public void setOadrTransports(OadrTransports value) {
            this.oadrTransports = value;
        }

    }

}
