//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 12:32:33 PM CDT 
//


package com.oadr2.b;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for oadrServiceNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="oadrServiceNameType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="EiEvent"/>
 *     &lt;enumeration value="EiOpt"/>
 *     &lt;enumeration value="EiReport"/>
 *     &lt;enumeration value="EiRegisterParty"/>
 *     &lt;enumeration value="OadrPoll"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "oadrServiceNameType")
@XmlEnum
public enum OadrServiceNameType {

    @XmlEnumValue("EiEvent")
    EI_EVENT("EiEvent"),
    @XmlEnumValue("EiOpt")
    EI_OPT("EiOpt"),
    @XmlEnumValue("EiReport")
    EI_REPORT("EiReport"),
    @XmlEnumValue("EiRegisterParty")
    EI_REGISTER_PARTY("EiRegisterParty"),
    @XmlEnumValue("OadrPoll")
    OADR_POLL("OadrPoll");
    private final String value;

    OadrServiceNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OadrServiceNameType fromValue(String v) {
        for (OadrServiceNameType c: OadrServiceNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
