//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 12:32:33 PM CDT 
//


package com.oadr2.b;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for oadrSamplingRateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oadrSamplingRateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="oadrMinPeriod" type="{urn:ietf:params:xml:ns:icalendar-2.0}DurationValueType"/>
 *         &lt;element name="oadrMaxPeriod" type="{urn:ietf:params:xml:ns:icalendar-2.0}DurationValueType"/>
 *         &lt;element name="oadrOnChange" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oadrSamplingRateType", propOrder = {
    "oadrMinPeriod",
    "oadrMaxPeriod",
    "oadrOnChange"
})
@XmlRootElement(name = "oadrSamplingRate")
public class OadrSamplingRate {

    @XmlElement(required = true)
    protected String oadrMinPeriod;
    @XmlElement(required = true)
    protected String oadrMaxPeriod;
    protected boolean oadrOnChange;

    /**
     * Gets the value of the oadrMinPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOadrMinPeriod() {
        return oadrMinPeriod;
    }

    /**
     * Sets the value of the oadrMinPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOadrMinPeriod(String value) {
        this.oadrMinPeriod = value;
    }

    /**
     * Gets the value of the oadrMaxPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOadrMaxPeriod() {
        return oadrMaxPeriod;
    }

    /**
     * Sets the value of the oadrMaxPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOadrMaxPeriod(String value) {
        this.oadrMaxPeriod = value;
    }

    /**
     * Gets the value of the oadrOnChange property.
     * 
     */
    public boolean isOadrOnChange() {
        return oadrOnChange;
    }

    /**
     * Sets the value of the oadrOnChange property.
     * 
     */
    public void setOadrOnChange(boolean value) {
        this.oadrOnChange = value;
    }

}
