//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 12:32:33 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://openadr.org/oadr-2.0b/2012/07", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.oadr2.b;
