//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 12:32:33 PM CDT 
//


package com.oadr2.b;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reportNameEnumeratedType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="reportNameEnumeratedType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="METADATA_HISTORY_USAGE"/>
 *     &lt;enumeration value="HISTORY_USAGE"/>
 *     &lt;enumeration value="METADATA_HISTORY_GREENBUTTON"/>
 *     &lt;enumeration value="HISTORY_GREENBUTTON"/>
 *     &lt;enumeration value="METADATA_TELEMETRY_USAGE"/>
 *     &lt;enumeration value="TELEMETRY_USAGE"/>
 *     &lt;enumeration value="METADATA_TELEMETRY_STATUS"/>
 *     &lt;enumeration value="TELEMETRY_STATUS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "reportNameEnumeratedType", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110")
@XmlEnum
public enum ReportNameEnumeratedType {

    METADATA_HISTORY_USAGE,
    HISTORY_USAGE,
    METADATA_HISTORY_GREENBUTTON,
    HISTORY_GREENBUTTON,
    METADATA_TELEMETRY_USAGE,
    TELEMETRY_USAGE,
    METADATA_TELEMETRY_STATUS,
    TELEMETRY_STATUS;

    public String value() {
        return name();
    }

    public static ReportNameEnumeratedType fromValue(String v) {
        return valueOf(v);
    }

}
