//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 12:32:33 PM CDT 
//


package com.oadr2.b;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseRequiredType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResponseRequiredType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="always"/>
 *     &lt;enumeration value="never"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResponseRequiredType")
@XmlEnum
public enum ResponseRequiredType {


    /**
     * Always send a response for every event received.
     * 
     */
    @XmlEnumValue("always")
    ALWAYS("always"),

    /**
     * Never respond.
     * 
     */
    @XmlEnumValue("never")
    NEVER("never");
    private final String value;

    ResponseRequiredType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResponseRequiredType fromValue(String v) {
        for (ResponseRequiredType c: ResponseRequiredType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
