//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 12:32:33 PM CDT 
//


package com.oadr2.b;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A customer ServiceLocation has one or more ServiceDeliveryPoint(s), which in turn relate to Meters. The location may be a point or a polygon, depending on the specific circumstances. For distribution, the ServiceLocation is typically the location of the utility customer's premise. 
 * 
 * <p>Java class for ServiceLocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceLocationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}FeatureCollection"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceLocationType", namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power", propOrder = {
    "featureCollection"
})
@XmlRootElement(name = "serviceLocation", namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power")
public class ServiceLocation {

    @XmlElement(name = "FeatureCollection", namespace = "http://www.opengis.net/gml/3.2", required = true)
    protected FeatureCollection featureCollection;

    /**
     * Gets the value of the featureCollection property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureCollection }
     *     
     */
    public FeatureCollection getFeatureCollection() {
        return featureCollection;
    }

    /**
     * Sets the value of the featureCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureCollection }
     *     
     */
    public void setFeatureCollection(FeatureCollection value) {
        this.featureCollection = value;
    }

}
